### ISSUE TITLE
db folder not created by lein

### ISSUE THREAD

**Issue by danpicton** [chrishowejones/blog-film-handler#1]
I found that running:
`lein new duct film-ratings +site +ataraxy +sqlite +example`

Didn't create the db folder as stated in the [blog post](https://circleci.com/blog/build-a-clojure-web-app-using-duct/). The following error was encountered on issuing the `(go)` fn:
```
user=> (dev)
:loaded
dev=> (go)

SQLException path to 'db/dev.sqlite': '/home/dan/projects/clojure/blog-film-ratings/db' does not exist  org.sqlite.core.CoreConnection.open (CoreConnection.java:192)
```
When I created the db folder, things worked as expected.

For reference, I'm using Leiningen 2.8.1 on Java 1.8.0_201 Java HotSpot(TM) 64-Bit Server VM.

**Comment by chrishowejones** [comment]
I'll take a look when I get a chance.

**Comment by chrishowejones** [comment]
@danpicton Hmm, not sure what's going on but I've tried it several times and it always creates the db/ dir as part of the lein template. Maybe there was a bug introduced to the template which has now been resolved? Anyway glad you figured out how to get around it.
